#!/usr/bin/env python3
"""Bundle training_pipeline.py into kaggle_train.py for Kaggle script kernels."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PIPELINE = (ROOT / "kaggle" / "training_pipeline.py").read_text(encoding="utf-8")
KAGGLE_TAIL = """

OUTPUT_DIR = Path("/kaggle/working/artifacts")


def resolve_data_path_kaggle():
    search_roots = [
        Path("/kaggle/input/datasets/alexteboul/diabetes-health-indicators-dataset"),
        Path("/kaggle/input/diabetes-health-indicators-dataset"),
        Path("/kaggle/input/alexteboul-diabetes-health-indicators-dataset"),
    ]
    for root in Path("/kaggle/input").rglob("*"):
        if root.is_dir() and "diabetes-health-indicators" in root.name.lower():
            search_roots.append(root)

    seen = set()
    for root in search_roots:
        if root in seen or not root.exists():
            continue
        seen.add(root)
        for name in PREFERRED_CSV_NAMES:
            candidate = root / name
            if candidate.is_file():
                return candidate
        csv_files = sorted(root.glob("*.csv"))
        if csv_files:
            return csv_files[0]

    for name in PREFERRED_CSV_NAMES:
        matches = sorted(Path("/kaggle/input").rglob(name))
        if matches:
            return matches[0]

    available = sorted(str(path) for path in Path("/kaggle/input").rglob("*.csv"))
    raise FileNotFoundError(
        "Could not find the diabetes indicators CSV under /kaggle/input. "
        f"Available CSV files: {available or 'none'}"
    )


def load_dataset():
    data_path = resolve_data_path_kaggle()
    print(f"Loading dataset from {data_path}")
    df = pd.read_csv(data_path)
    missing = [column for column in [TARGET_COLUMN, *FEATURE_NAMES] if column not in df]
    if missing:
        raise ValueError(f"Dataset is missing required columns: {', '.join(missing)}")
    return data_path, df[FEATURE_NAMES].copy(), df[TARGET_COLUMN].astype(int)


def main():
    data_path, X, y = load_dataset()
    train_production_model(X, y, data_path=data_path, output_dir=OUTPUT_DIR)


if __name__ == "__main__":
    main()
"""

header = (
    "# Auto-generated by scripts/sync_kaggle_train.py - do not edit by hand.\n"
    "# Source: kaggle/training_pipeline.py\n\n"
)
out = ROOT / "kaggle" / "kaggle_train.py"
out.write_text(header + PIPELINE + KAGGLE_TAIL, encoding="utf-8")
print(f"Wrote {out}")
